CR Changes

diff --git a/.github/workflows/test-public-fe.yml b/.github/workflows/test-public-fe.yml
--- a/.github/workflows/test-public-fe.yml
+++ b/.github/workflows/test-public-fe.yml
@@ -96,11 +96,11 @@ jobs:
             - uses: actions/checkout@v3
 
             - uses: actions/setup-node@v3
+              with:
+                  node-version: '22'
 
             - name: Test connection between FE and BE
-              run: |-
-                  echo "Testing connection to BE API"
-                  docker exec web-public-fe wget -qO- http://web-public-be:8080/me || (echo "Connection test failed" && exit 1)
+              run: docker exec web-public-fe wget -qO- http://web-public-be:8080/me || (echo "Connection test failed" && exit 1)
 
             - name: run tests
               run: |-
